### PR TITLE
Unit 5.2

### PR DESCRIPTION
**Pull request by jackvangent**
Implements 5.1 and 5.2, refactored a bunch of stuff, changed minimize function from section 3 to use angular.

### CODE REVIEW

**Comment by chadcallahan** [comment]
@jackvangent Looks like you missed a step.  Unit 4 says to use npm to install your dependencies (angular, ui-router, resource).  The reason we do this is so that the repository doesn't include those 3rd party library files.  

Your readme file should include instructions on what needs done in order for anyone to be able to clone your repository and get it to run locally.  Once you have your project using npm, add that as an installation step to your readme (need to run 'npm install' to install the dependencies defined in your package.json file).

Also, make sure that you create a .gitignore file and add node_modules/ to it.  If you don't, then you'll likely end up pushing your node_modules folder to the remote repository, which would defeat the purpose of even using npm (if we're going to host our 3rd party libs in our repository, why even bother with a package manager?).

**Comment by chadcallahan** [comment]
@jackvangent You can reopen this same pull request once those adjustments have been made.

**Comment by jackvangent** [comment]
Step 4 is done (I think).

**Comment by chadcallahan** [comment]
@jackvangent Perfect!

**Pull request merged**
